"""add avatar gender fields 0929 --Lihao

Revision ID: 2deaac3bfde7
Revises: d107a7c39788
Create Date: 2020-09-29 15:19:22.530663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2deaac3bfde7'
down_revision = 'd107a7c39788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user', sa.Column('avatar_url', sa.Text(), nullable=True))
    op.add_column('tb_user', sa.Column('device_message', sa.Text(), nullable=True))
    op.add_column('tb_user', sa.Column('gender', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_user', 'gender')
    op.drop_column('tb_user', 'device_message')
    op.drop_column('tb_user', 'avatar_url')
    # ### end Alembic commands ###
