"""init database 0929 --Lihao

Revision ID: 3f99eba0783e
Revises: 
Create Date: 2020-09-29 11:26:06.498080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f99eba0783e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('real_name', sa.String(length=50), nullable=True),
    sa.Column('nick_name', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('open_id', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('device_message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_user_mobile'), 'tb_user', ['mobile'], unique=True)
    op.create_index(op.f('ix_tb_user_nick_name'), 'tb_user', ['nick_name'], unique=False)
    op.create_index(op.f('ix_tb_user_open_id'), 'tb_user', ['open_id'], unique=True)
    op.create_index(op.f('ix_tb_user_real_name'), 'tb_user', ['real_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_user_real_name'), table_name='tb_user')
    op.drop_index(op.f('ix_tb_user_open_id'), table_name='tb_user')
    op.drop_index(op.f('ix_tb_user_nick_name'), table_name='tb_user')
    op.drop_index(op.f('ix_tb_user_mobile'), table_name='tb_user')
    op.drop_table('tb_user')
    # ### end Alembic commands ###
