"""delete device_message field 0929 --Lihao

Revision ID: d107a7c39788
Revises: 3f99eba0783e
Create Date: 2020-09-29 13:09:28.435252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd107a7c39788'
down_revision = '3f99eba0783e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_user', 'device_message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user', sa.Column('device_message', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
